version: 3

sources:
  - name: rma_salesforce
    database: PC_FIVETRAN_DB
    schema: SALESFORCE
    tables:
      - name: CONTACT
  - name: rma_postgres
    database: PC_FIVETRAN_DB
    schema: POSTGRES_PUBLIC
    tables:
      - name: SALES_TRANSACTIONS
